# Generated by rust2rpm 9
%bcond_with check
%global debug_package %{nil}

%global crate libflate

Name:           rust-%{crate}
Version:        0.1.23
Release:        3%{?dist}
Summary:        Rust implementation of DEFLATE algorithm and related formats (ZLIB, GZIP)

# Upstream license specification: MIT
License:        MIT
URL:            https://crates.io/crates/libflate
Source:         %{crates_source}

ExclusiveArch:  %{rust_arches}

BuildRequires:  rust-packaging
BuildRequires:  (crate(adler32/default) >= 1.0.0 with crate(adler32/default) < 2.0.0)
BuildRequires:  (crate(byteorder/default) >= 1.0.0 with crate(byteorder/default) < 2.0.0)
BuildRequires:  (crate(crc32fast/default) >= 1.0.0 with crate(crc32fast/default) < 2.0.0)
%if %{with check}
BuildRequires:  (crate(clap/default) >= 2.0.0 with crate(clap/default) < 3.0.0)
%endif

%global _description %{expand:
Rust implementation of DEFLATE algorithm and related formats (ZLIB, GZIP).}

%description %{_description}

%package        devel
Summary:        %{summary}
BuildArch:      noarch

%description    devel %{_description}

This package contains library source intended for building other packages
which use "%{crate}" crate.

%files          devel
%license LICENSE
%doc README.md
%{cargo_registry}/%{crate}-%{version}/

%package     -n %{name}+default-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+default-devel %{_description}

This package contains library source intended for building other packages
which use "default" feature of "%{crate}" crate.

%files       -n %{name}+default-devel
%ghost %{cargo_registry}/%{crate}-%{version}/Cargo.toml

%prep
%autosetup -n %{crate}-%{version_no_tilde} -p1
%cargo_prep

%build
%cargo_build

%install
%cargo_install

%if %{with check}
%check
%cargo_test
%endif

%changelog
* Thu Jan 30 2020 Fedora Release Engineering <releng@fedoraproject.org> - 0.1.23-3
- Rebuilt for https://fedoraproject.org/wiki/Fedora_32_Mass_Rebuild

* Fri Jul 26 2019 Fedora Release Engineering <releng@fedoraproject.org> - 0.1.23-2
- Rebuilt for https://fedoraproject.org/wiki/Fedora_31_Mass_Rebuild

* Thu May 30 17:37:49 CEST 2019 Igor Gnatenko <ignatenkobrain@fedoraproject.org> - 0.1.23-1
- Update to 0.1.23

* Mon Apr 15 2019 Josh Stone <jistone@redhat.com> - 0.1.22-1
- Update to 0.1.22

* Wed Mar 13 2019 Igor Gnatenko <ignatenkobrain@fedoraproject.org> - 0.1.21-1
- Update to 0.1.21

* Tue Feb 19 2019 Igor Gnatenko <ignatenkobrain@fedoraproject.org> - 0.1.20-1
- Update to 0.1.20

* Sat Feb 02 2019 Fedora Release Engineering <releng@fedoraproject.org> - 0.1.19-3
- Rebuilt for https://fedoraproject.org/wiki/Fedora_30_Mass_Rebuild

* Sat Jan 26 2019 Igor Gnatenko <ignatenkobrain@fedoraproject.org> - 0.1.19-2
- Run tests in infrastructure

* Sat Jan 26 2019 Igor Gnatenko <ignatenkobrain@fedoraproject.org> - 0.1.19-1
- Initial package
